site_name: mkdocs
site_description: mkdocs
site_author: zhenfeng.zhao

repo_name: 'github'
repo_url: 'https://one-pig1.github.io/mkdocs/'

theme:
  name: material
  language: 'zh'

extra:
  social:
    - type: github
      link: https://github.com/one-pig1
    - type: gitee
      link: https://gitee.com/one_pig1
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
    # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
    - index.md
    # - mkdocs:
    - 一. 介绍: mkdocs/文档.md
    - 二. 安装:
        - 1. 本地环境搭建: mkdocs/install/local.md
        - 2. 发布至GitHub Pages: mkdocs/install/github-pages.md
        - 3. 发布至自己的HTTP Server: mkdocs/install/http-server.md
    - 三. 语法:
        - 1. 语法总览: mkdocs/syntax/main.md
        - 2. 标题: mkdocs/syntax/headline.md
        - 3. 段落: mkdocs/syntax/paragraph.md
        - 4. 引用: mkdocs/syntax/quote.md
        - 5. 表格: mkdocs/syntax/table.md
        - 6. 代码:
            - 6.1. 行内: mkdocs/syntax/code_inline.md
            - 6.2. 区块: mkdocs/syntax/code_block.md
            - 6.3. 高亮: mkdocs/syntax/code_highlight.md
        - 7. 字体样式:
            - 7.1. 斜体,粗体,粗斜体: mkdocs/syntax/font_stress.md
            - 7.2. 上标,下标: mkdocs/syntax/font_updown.md
            - 7.3. 下划线: mkdocs/syntax/font_underline.md
            - 7.4. 横线: mkdocs/syntax/font_line.md
            - 7.5. 下划线+横线: mkdocs/syntax/font_underline_line.md
        - 8. 列表:
            - 8.1. 无序列表: mkdocs/syntax/list_noseq.md
            - 8.2. 有序列表: mkdocs/syntax/list_seq.md
            - 8.3. 任务列表: mkdocs/syntax/list_task.md
        - 9. 分割线: mkdocs/syntax/cutline.md
        - 10. 链接:
            - 10.1. 普通链接: mkdocs/syntax/link_normal.md
            - 10.2. 自动链接: mkdocs/syntax/link_auto.md
            - 10.3. 锚点提示: mkdocs/syntax/link_anchor.md
        - 11. 图片:
            - 11.1. 行内式: mkdocs/syntax/image_inline.md
            - 11.2. 参考式: mkdocs/syntax/image_index.md
        - 12. 转义: mkdocs/syntax/escape.md
        - 13. 高亮:
            - 13.1. 代码高亮: mkdocs/syntax/highlight_code.md
            - 13.2. 背景高亮: mkdocs/syntax/highlight_background.md
        - 14. 注解:
            - 14.1. 介绍: mkdocs/syntax/note_main.md
            - 14.2. 完整格式: mkdocs/syntax/note_full.md
            - 14.3. 空标题: mkdocs/syntax/note_empty-title.md
            - 14.4. 无标题: mkdocs/syntax/note_none-title.md
            - 14.5. 无类型: mkdocs/syntax/note_none-type.md
            - 14.6. 折叠: mkdocs/syntax/note_details.md
            - 14.7. 11种颜色样式: mkdocs/syntax/note_style.md
            - 14.8. 嵌套: mkdocs/syntax/note_nest.md
        - 15. 脚注: mkdocs/syntax/footnote.md
        - 16. 元信息: mkdocs/syntax/meta.md
        - 17. 数学公式:
            - 17.1. 介绍: mkdocs/syntax/math_main.md
            - 17.2. 导入js: mkdocs/syntax/math_js.md
            - 17.3. 用法: mkdocs/syntax/math_usage.md
        - 18. emoji:
            - 18.1. 介绍: mkdocs/syntax/emoji_main.md
            - 18.2. 工作原理: mkdocs/syntax/emoji_principle.md
            - 18.3. 最佳实践: mkdocs/syntax/emoji_usage.md
        - 19. 特殊符号: mkdocs/syntax/symbol.md
        - 20. 嵌套:
            - 20.1. 介绍: mkdocs/syntax/nest_main.md
            - 20.2. 注解-注解: mkdocs/syntax/nest_note_note.md
            - 20.3. 列表-列表: mkdocs/syntax/nest_list_list.md
            - 20.4. 引用-引用: mkdocs/syntax/nest_quote_quote.md
            - 20.5. 注解-代码块: mkdocs/syntax/nest_note_code.md
            - 20.6. 列表-代码块: mkdocs/syntax/nest_list_code.md
            - 20.7. 引用-代码块: mkdocs/syntax/nest_quote_code.md
            - 20.8. 黄色区块-代码: mkdocs/syntax/nest_yellow_code.md
            - 20.9. 绿色区块-代码: mkdocs/syntax/nest_green_code.md
            - 20.10. 红色区块-代码: mkdocs/syntax/nest_red_code.md
            - 20.11. 绿接红区块-代码: mkdocs/syntax/nest_greenred_code.md
            - 20.12. 注解-列表-引用: mkdocs/syntax/nest_note_list_quote.md
            - 20.13. 列表-列表-引用: mkdocs/syntax/nest_list_list_quote.md
            - 20.14. 引用-引用-代码: mkdocs/syntax/nest_quote_quote_code.md
    - 四. 附录:
        - 1. 支持代码高亮的语言: mkdocs/appendix/pygments.md
        - 2. emojione全名短名映射表: mkdocs/appendix/emoji_shortname.md
        - 3. 添加百度统计: mkdocs/appendix/baidu_tongji.md
        - 4. 配色: mkdocs/appendix/color.md
        - 5. 模块介绍: mkdocs/appendix/module.md
        - 6. mkdocs层级关系: mkdocs/appendix/level.md
        - 7. 支持中文搜索: mkdocs/appendix/search.md
        - 8. mkdocs.yml范例: mkdocs/appendix/yml.md
    - 五. 使用建议: mkdocs/recommend.md
    - 六. 联系方式: mkdocs/contact.md
